### ISSUE TITLE
Broken Link for "Usulkan Aktivitas" Button?

### ISSUE THREAD

**Issue by zakiego** [senar-ai/web#1]
![Screenshot from 2022-06-05 14-51-04](https://user-images.githubusercontent.com/78015359/172039255-e9241b6a-ee3b-4844-af0a-31d09215bcd0.png)
![Screenshot from 2022-06-05 14-51-30](https://user-images.githubusercontent.com/78015359/172039257-5fc46895-e92f-495c-866d-40c69e3e03a3.png)

I don't know exactly where the problem is, I can't run it locally because there are paid libraries. 😅

But maybe the problem is here?
https://github.com/senar-ai/web/blob/518a15ddb6a682376b6c1360623736ab1e4087b1/app/components/activities-grid.tsx#L15

**Comment by zainfathoni** [comment]
Thanks for reporting this issue!

I just fixed it in this commit. https://github.com/senar-ai/web/commit/4615832225cd8229f693c38a0da4b879d643a172
