### ISSUE TITLE
Rethinking pro version of fortawesome

### ISSUE THREAD

**Issue by mazipan** [senar-ai/web#2]
We can not use the pro version since it needs a token to download the icon.

It blocks the other contributors to run the code locally.

Or is there any way to share the token to other contributors?
Not sure about the legality and the security just by sharing the token.

**Comment by zainfathoni** [comment]
I'll try to find a way to make it easier to contribute.
Extracting the SVG files is one of the possible alternatives.

**Comment by zainfathoni** [comment]
I removed the dependencies to the Font Awesome Pro license in this commit https://github.com/senar-ai/web/commit/6c2baa6514b47ff2aee0e87ec6851841ce65d73f.

Now any contributors should be able to run this project without needing a license.
